version: "3.9"
services:
  postgres:
    container_name: postgresql
    image: postgres:16.1-alpine3.19
    restart: unless-stopped
    environment:
      - POSTGRES_USER=pg-user
      - POSTGRES_PASSWORD=pg-pass
      - POSTGRES_DB=keycloak-db
      - POSTGRES_DB_SCHEMA=keycloak-schema
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./keycloak/db/:/docker-entrypoint-initdb.d/
    networks:
      - auth-network
    healthcheck:
      test: [ 'CMD-SHELL', 'sh', '-c', 'psql', '-U', 'pg-user', '-d', 'keycloak-db', '-c', 'SELECT schema_name FROM information_schema.schemata WHERE schema_name = ''keycloak-schema''' ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    container_name: keycloak
    image: bitnami/keycloak:23.0.6
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=postgres # default
      - KEYCLOAK_DATABASE_PORT=5432 # default
      - KEYCLOAK_DATABASE_USER=pg-user
      - KEYCLOAK_DATABASE_PASSWORD=pg-pass
      - KEYCLOAK_DATABASE_NAME=keycloak-db
      - KEYCLOAK_DATABASE_SCHEMA=keycloak-schema
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./keycloak/themes/:/opt/bitnami/keycloak/themes/
    networks:
      - auth-network

volumes:
  postgres:
    driver: local
  pgadmin-data:
    driver: local
networks:
  auth-network:
    name: auth-network
    driver: bridge